/**
 * Define the dashboard configuration.
 */
export type DashboardConfig = {
  type?: "dashboard" | "group";
  /**
   * Internal ID of the dashboard.
   * Required to query the API and obtain full dashboard infoes required to
   * do more than just rendering the dashboard.
   */
  id: number;
  /**
   * Indicate if the dashboard the default one to display on the home page.
   */
  home?: boolean;
  /**
   * The uuid generated by Superset.
   * Required to build the URL to the dashboard and render it finally.
   */
  uuid: string;
  /**
   * The slug used to access the dashboard. Usefull for SEO and to match the
   * URL with the dashboard when the user clicks on a link.
   */
  slug: string;
  /**
   * The name of the dashboard used to display it inside header menu.
   */
  name: string;
  /**
   * The menu item that will contain a link to this dashboard.
   */
  menu?: string;
  /**
   * Eventually a section inside the menu item that will contain a link to this.
   */
  section?: string;
  /**
   * Indicate if this dashboard should pass from the filter page before rendering.
   */
  prefilter?: boolean;
  /**
   * Specify any filter to apply on the dashboard
   */
  filter?: Array<string>;
  /**
   * List of dashboards to display togheter.
   * You must specify the slug of the dashboard.
   */
  dashboards?: string[];
};

/**
 * Define how to implement config providers.
 */
export interface ConfigProviderInterface {
  getAllDashboards(): DashboardConfig[];
  /** Get the dashboard configuration by its slug. */
  getHomePageDashboardConfig(): DashboardConfig | undefined;
  /** Retrieve list of dashboards to display. */
  getDashboardConfigs(): DashboardConfig[];
  /** Get the dashboard configuration by its slug. */
  getDashboardConfigBySlug(slug: string): DashboardConfig | undefined;
  /** Get the dashboard configuration by its uuid. */
  getDashboardConfigByUuid(uuid: string): DashboardConfig | undefined;
  /** Get the dashboard configuration by its id. */
  getDashboardConfigById(id: number): DashboardConfig | undefined;
  /** Get the dashboard configuration by its slug, uuid or id. */
  getDashboardConfig(identifier: string | number): DashboardConfig | undefined;
}
